### Configuration minimale
site_name: ADN - Tutoriel site web # Nom du site <70 caractères, apparait dans l'onglet du navigateur 
site_url: https://ericecmorlaix.github.io/adn-Tutoriel_site_web/ # Adresse web principale de publication du site

### Configuration du dépôt
# Ajoute en haut à droite de chaque page du site, icône, nom et lien vers le dépot GitHub du projet.
repo_url: https://github.com/ericECmorlaix/adn-Tutoriel_site_web/
repo_name: adn-Tutoriel_site_web # Personnalise le nom générique "GitHub" donné par défaut au lien vers le dépot GitHub du projet.
edit_uri: edit/main/docs/ # Complément au chemin pour aller depuis `repo_url:` jusqu'au répertoire `docs` ;
# Ce qui permet avec MkDocs-Material d'ajouter un bouton (crayon) d'édition du code source.md d'une page du site depuis le navigateur
# (edit => édition avec connexion | blob, tree => lecture anonyme)

### Configuration de métadonnées
# Métadonnées de description <300 caratères, et d'auteur pour toutes les pages du site 
site_description: >
    Tutoriel pour créer et gérer un site web depuis un dépôt git
    avec le framework material pour mkdocs et des notebook jupyter
site_author: "Eric MADEC"

### Configuration de la stucture de navigation
# Dossier source, chemin relatif au fichier mkdocs.yml
docs_dir: docs
# Structure du menu principal de navigation, chemins relatifs au dossier docs_dir
nav:
- Accueil: index.md
- Créer, déployer puis maintenir son site:
    Dans un navigateur: PremiersPas.md
    Sur PC avec Visual Studio Code: PCW10-VSC.md
    Sur iPad en ligne de commande: iPad.md
- Coder pour générer ses pages web:
    MarkDown Mkdocs-Material, le contenu: MarkDown-Mkdocs_Material.md
    YAML, la configuration: Yaml.md
    LaTeX, les sciences: LaTeX.md
    Python, les macros: Python.md
- Ressources : Ressources.md 
   
# Configuration du thème https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
theme:
    name: material # autres thèmes : https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
    custom_dir: overrides #  
    font: false  # RGPD ; pas de fonte Google
    language: fr # français
    logo: images/LogoIO.png # image qui apparait dans l'en tête à gauche du titre de la page
    # et qui est support du lien qui renvoie à la racine du site depuis toutes les pages
    favicon: images/LogoIO-pink.png # image qui apparait dans l'onglet du navigateur avant le titre du site
    # Palettes de couleurs jour/nuit, cf : https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    icon:
      repo: fontawesome/brands/github-alt # modifie l'icône du lien vers le dépot du projet de l'en tête
    palette: 
      - scheme: default # nom du thème clair
        primary: pink # couleur primaire des titres, des liens, ..., à prendre dans la liste
        accent: cyan # couleur d'accentuation au survol des boutons, desliens, ..., à prendre dans la liste
        toggle: # définition du bouton pour switcher de palette
          icon: material/weather-sunny # apparence
          name: Basculer en mode sombre # message
      - scheme: slate # nom du thème sombre
        primary: cyan
        accent: pink
        toggle:
          icon: material/weather-night
          name: Basculer en mode clair
    # Configuration du comportement de la navigation, cf : https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    features: 
        - navigation.instant # active XHR https://fr.wikipedia.org/wiki/XMLHttpRequest
        - navigation.tabs # Menu de navigation horizontal sous l'en-tête sauf sur appareil mobile
        # - navigation.tabs.sticky # Menu de navigation horizontal collant
        - navigation.top # bouton pour remonter tout en haut de la page
        - toc.integrate # Table Of Content, table des matières intégrée dans la barre verticale de navigation
        - header.autohide # masquage automatique de l'en tête du site lorsque l'on descend dans la page        

### Configuration des extensions MarkDown :        
markdown_extensions: # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
    # extensions de la bibliothèque markdown standard
    - abbr                          # Infobulles sur abbréviations 
    - meta                          # Métadonnées
    - def_list                      # Listes de définition.
    - attr_list                     # Sélecteurs CSS et attributs HTML personnalisés
    - md_in_html                    # Pour écrire en MarkDown dans des balises HTML https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Boite d'avertissements  !!! info "ma remarque"
    - toc:                          # Configuration de la table des matières générée automatiquement à partir des titres du niveau 2
        permalink: "&num;"          # Ajoute un symbole lien hypertexte vers l'ancre du titre #le-titre 
        toc_depth: 4                # Limite de la profondeur d'inclusion des titres dans la table des matières
    # extensions de python-markdown https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.details              # plier/déplier les avertissements.
    - pymdownx.caret                # texte ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # texte ==surligné==.
    - pymdownx.tilde                # texte ~~barré~~ ou en ~indice~.
    - pymdownx.critic               # Pour du marquage et commentaires de révision de texte
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    true    #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed               # Onglets coulissants.  === "Onglet"
    - pymdownx.superfences          # Imbrication de blocs.
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:          # Formules en LaTeX 
        generic: true
        smart_dollar: false

plugins:
  - search # Inclure une barre de recherche
  - mkdocs-jupyter: # Convertir les fichiers .ipynb et .py en pages du site https://github.com/danielfrg/mkdocs-jupyter
      include_source: True # Inclu une copie du fichier source.ipynb (ou .py) dans le dossier de la page sur le site pour son téléchargement
  - macros # ajout du mini-framework mkdocs-macros-plugin, https://mkdocs-macros-plugin.readthedocs.io/  

### Configuration d'une licence
# Information de droit d'auteur qui s'affiche dans le pied de page pour toutes les pages du site
copyright: >
    Document partagé par <a href="https://github.com/ericECmorlaix" target="_blank">Eric MADEC</a>
    &copy; 2021 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a>
    <br> Illustrations par <a href="https://undraw.co/" target="_blank">UnDraw</a>

### Configuration de liens sociaux https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links 
extra:
  social: 
    - icon: fontawesome/solid/paper-plane
      link: "mailto:eric.madec@ecmorlaix.fr?subject=ADN - Tutoriel documentation web&body=Votre question : ..."
      name: Pour toute question, suggestion ou commentaire, écrire à l'auteur
    - icon: fontawesome/brands/github
      link: https://github.com/ericECmorlaix/adn-Tutoriel_site_web
      name: dépôt github
    - icon: fontawesome/solid/university
      link: https://www.ecmorlaix.fr/nos-etablissements/lycee-notre-dame-du-mur/
      name: Lycée Notre Dame du Mur


extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
