# Paramètres obligatoires 
site_name: ADN - Tutoriel site web # Nom du site, apparait dans l'onglet du navigateur 
site_url: https://ericecmorlaix.github.io/adn-Tutoriel_site_web/ # Adresse web principale de publication du site

# Ajoute en haut à droite de chaque page du site, icône, nom et lien vers le dépot GitHub du projet.
repo_url: https://github.com/ericECmorlaix/adn-Tutoriel_site_web/
repo_name: adn-Tutoriel_site_web # Personnalise le nom générique "GitHub" donné par défaut au lien vers le dépot GitHub du projet.
edit_uri: edit/main/docs/ # Complément au chemin pour aller depuis `repo_url:` jusqu'au répertoire `docs` ; Ce qui permet avec MkDocs-Material un lien d'édition dans le navigateur du code source


# Métadonnées de description et d'auteur pour toutes les pages du site 
site_description: >
    Tutoriel pour créer et gérer un site web depuis un dépôt git 
    avec le framework material pour mkdocs et des notebook jupyter
site_author: "Eric MADEC"

# Information de droit d'auteur qui s'affiche dans le pied de page pour toutes les pages du site
copyright: >
    Document partagé par <a href="https://github.com/ericECmorlaix" target="_blank">Eric MADEC</a>
    &copy; 2021 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a>
    <br> Illustrations par <a href="https://undraw.co/" target="_blank">UnDraw</a>

# Structure des dossiers :
docs_dir: docs
# Menu principal de navigation
nav: 
  - Accueil: index.md
  - Créer, déployer puis maintenir son site:
    - Dans un navigateur: PremiersPas.md
    - Sur PC avec Visual Studio Code: PCW10-VSC.md
    - Sur iPad en ligne de commande: iPad.md
  - Coder pour générer ses pages web:
    - MarkDown Mkdocs-Material, le contenu: MarkDown-Mkdocs_Material.md
    - YAML, la configuration: Yaml.md
    - LaTeX, les sciences: LaTeX.md
    - Python, les macros: Python.md
  - Ressources : Ressources.md

   
# Définition du thème https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
theme:
    name: material
    custom_dir: overrides
    font: false  # RGPD ; pas de fonte Google
    language: fr # français
    logo: images/LogoIO.png 
    favicon: images/LogoIO-pink.png # Icone qui apparait dans l'onglet du navigateur avant le nom du site
    # Palettes de couleurs jour/nuit, cf : https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette: 
      - scheme: default # nom du thème clair
        primary: pink # couleur primaire des titres, des liens, ..., à prendre dans la liste
        accent: cyan # couleur d'accentuation au survol des boutons, desliens, ..., à prendre dans la liste
        toggle: # définition du bouton pour switcher de palette
          icon: material/weather-sunny # apparence
          name: Basculer en mode sombre # message
      - scheme: slate # nom du thème sombre
        primary: cyan
        accent: pink
        toggle:
          icon: material/weather-night
          name: Basculer en mode clair
    # Configuration de la navigation, cf : https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    features: 
        - navigation.instant 
        - navigation.tabs # Menu de navigation horizontal sous l'en-tête sauf sur appareil mobile
        # - navigation.tabs.sticky # Menu de navigation horizontal collant
        - navigation.top # bouton pour remonter tout en haut de la page
        - toc.integrate # Table Of Content, table des matières intégrée dans la barre verticale de navigation
        - header.autohide # masquage automatique de l'entête du site lorsque l'on descend dans la page        


markdown_extensions: # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
    # extensions de la bibliothèque markdown standard
    - abbr                          # Infobulles sur abbréviations 
    - meta                          # Métadonnées
    - def_list                      # Listes de définition.
    - attr_list                     # Sélecteurs CSS et attributs HTML personnalisés
    - md_in_html                    # Pour écrire en MarkDown dans des balises HTML https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Boite d'avertissements  !!! info "ma remarque"
    - toc:                          # Table des matières
        permalink: ⚓︎
        toc_depth: 4
    # extensions de python-markdown https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.details              # plier/déplier les avertissements.
    - pymdownx.caret                # texte ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # texte ==surligné==.
    - pymdownx.tilde                # texte ~~barré~~ ou en ~indice~.
    - pymdownx.critic               # Pour du marquage et commentaires de révision de texte
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    true    #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed               # Onglets coulissants.  === "Onglet"
    - pymdownx.superfences          # Imbrication de blocs.
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:          # Formules en LaTeX 
        generic: true
        smart_dollar: false

plugins:
  - search # Inclure une barre de recherche
  - mkdocs-jupyter: # Convertir les fichiers .ipynb et .py en pages du site https://github.com/danielfrg/mkdocs-jupyter
      kernel_name: python3
      execute: False
      include_source: True


extra:
  social: 
    - icon: fontawesome/solid/paper-plane
      link: mailto:eric.madec@ecmorlaix.fr
      name: Pour toute question, suggestion ou commentaire, écrire à l'auteur
    - icon: fontawesome/brands/github
      link: https://github.com/ericECmorlaix/adn-Tutoriel_site_web
      name: dépôt github
    - icon: fontawesome/solid/university
      link: https://www.ecmorlaix.fr/nos-etablissements/lycee-notre-dame-du-mur/
      name: Lycée Notre Dame du Mur


extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
